export const authenticationType = {
    IS_AUTHENTIACTED: 'IS_AUTHENTIACTED',
    SET_USER_ID: 'SET_USER_ID',
    SET_USER_TOKEN: 'SET_USER_TOKEN',
    SET_CURRENT_ACCOUNT: 'SET_CURRENT_ACCOUNT',
    SET_USER_PERMISSION: 'SET_USER_PERMISSION'
}